name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
    - 'app/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

#     - name: Login to DockerHub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./app
        file: ./app/Dockerfile
        push: false
        tags: msmall318/app:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
