name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
    paths:
    - 'app/**'
    - '.github/workflows/docker-image.yml'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'app/**'
    - '.github/workflows/docker-image.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Docker compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build services
      run: |
        cd app
        docker-compose build
